# Generated by Django 6.0.3 on 2026-03-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_address', models.CharField(max_length=255)),
                ('arrival_address', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
