# Generated by Django 6.0.3 on 2026-03-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='tracking_number',
            field=models.CharField(default='TRK00000000', max_length=11),
        ),
    ]
