# Generated by Django 6.0.3 on 2026-03-15 19:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_parcel_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
